### ISSUE TITLE
AMD modules

### ISSUE THREAD

**Issue by mitermayer** [ramitos/jsctags#15]
AMD modules return just the top level names.

**Comment by hendrixski** [comment]
+1
I've tried setting my .tern-project and .tern-config files to support requirejs and I still get nothing. 
My files seem to work well with Tern itself, in my vim project I can use the tern commands. I hope this project isn't as dead as doctorjs :-(

**Comment by hushicai** [comment]
try hushicai/jsctags@99957656c818ea9f5cb9da4974039079b64a9fd9

**Comment by ldong** [comment]
@hushicai your patch works on backbone, does not work on jQuery, you can try to download jQuery  v1.10.2 as one example.

**Comment by faceleg** [comment]
@hushicai could you submit a PR?

**Comment by mitermayer** [comment]
@hushicai  can you submit a PR ?

**Comment by mitermayer** [comment]
@ramitos @hushicai  can you please state whats the status of the Pull request ?? should we start using @hushicai  branch ?? Should we move @hushicai  branch to a new project ?? I dont want to see this project dying
