### ISSUE TITLE
jsctags for JSX

### ISSUE THREAD

**Issue by khanghoang** [ramitos/jsctags#17]
Hi there,

I just wanna ask that do we support jsx file (React), if not then do we have plan to support it?

**Comment by zeusdeux** [comment]
I doubt this will happen till tern adds support for jsx since this project is dependent on tern.

**Comment by faceleg** [comment]
Does tern support JSX yet?

**Comment by ramitos** [comment]
To accomplish that we need to use tern-react when it detects a jsx file. But I'm not sure tern-react is ready yet

**Comment by faceleg** [comment]
This should now work, thanks to @ramitos, with the caveat that JSX tags get reported as booleans.
