### ISSUE TITLE
Unable to install with given npm syntax using npm 1.4.28

### ISSUE THREAD

**Issue by tecfu** [ramitos/jsctags#18]
### [1] The following terminal command syntax fails:

The following installation command fails for me on Ubuntu 14.04 / npm 1.4.28:
```
npm install -g git://github.com/ramitos/jsctags.git
```

But this succeeds and is logically equivalent: 
```
npm install -g git+https://github.com/ramitos/jsctags.git
```

### [2] The following package.json syntax fails:
```
"tern": "git://github.com/marijnh/tern.git",
```

But this succeeds and is logically equivalent:
```
"tern": "latest",
```

**Comment by tecfu** [comment]
Issued pull request: https://github.com/ramitos/jsctags/pull/19

**Comment by faceleg** [comment]
Thanks!
