### ISSUE TITLE
Error: Cannot find module '../../../narcissus/lib/parser'

### ISSUE THREAD

**Issue by anapitupulu** [ramitos/jsctags#21]
I got that error when running simple jsctags, e.g.: 

`jsctags src/slick.grid.js`

I tried to install narcissus manually but got another error. Before I debug further, is there anything simple I am missing?

**Comment by jalcine** [comment]
I've been having this issue for a while but ignoring it.

**Comment by anapitupulu** [comment]
@jalcine so how do you make it work? My jsctags quits immediately after that error...

**Comment by jalcine** [comment]
@anapitupulu I mentioned that I've just ignored the error for now

**Comment by faceleg** [comment]
Is this still happening?

**Comment by faceleg** [comment]
Closing as I can't replicate (nor do the tests)

**Comment by jalcine** [comment]
If I can isolate it, I'll make a new issue, but right now, it's one of those :ghost: bugs.

**Comment by faceleg** [comment]
Yes please do! 

I'm on a campaign to fix or encourage the fixing of all issues in this repo - we JS developers deserve and demand a fully featured CTags tool!
