### ISSUE TITLE
report every symbol, not only the ones in the global scope

### ISSUE THREAD

**Issue by ramitos** [ramitos/jsctags#3]
depends on marijnh/tern

**Comment by hoschi** [comment]
+1
tags for all symbols would be great

**Comment by mitermayer** [comment]
@ramitos any news on this issue???

**Comment by ryanoasis** [comment]
:+1:

**Comment by unphased** [comment]
@ramitos Have you looked into UglifyJS2?

Honestly, the task of extracting the places where functions begin is a task that `sed` can accomplish which I have not seen any javascript ctags system succeed at. Mainly because functions can be inside of yet other functions in Javascript.

**Comment by faceleg** [comment]
Is this still on the map? ETA?

**Comment by ramitos** [comment]
just pushed a branch with this working. Needs to be validated with tests: https://github.com/ramitos/jsctags/tree/ramos/recursive

**Comment by hoschi** [comment]
With the file:
```
function test () {
    return function inner () {
        return "foo"
    }
}
```

Output from `jsctags test.js` is:
```
nfbe-proto > jsctags test.js                                     
[
  {
    "id": "b3db27c0-e3b8-11e5-9a0a-57de7838abd7",
    "name": "test",
    "addr": "/test/",
    "kind": "f",
    "type": "string function() function()",
    "lineno": 1,
    "origin": {
      "!span": "9[0:9]-13[0:13]",
      "!type": "fn() -> fn() -> string",
      "!data": {
        "isConstructor": false,
        "type": "Function.prototype"
      }
    },
    "tagfile": "/home/hoschi/repos/nfbe/nfbe-proto/test.js"
  }
]
```

Which doesn't include the function `inner` :(
