### ISSUE TITLE
Dependency issue about ramitos/tern-jsx

### ISSUE THREAD

**Issue by Joouis** [ramitos/jsctags#55]
Hi, I wrote a plugin for Atom editor named [structure-view](https://github.com/alibaba/structure-view), which uses `jsctags` to parse AST tree of JS code. 

Since your package required a Github repo in `package.json`:
```json
"tern-jsx": "ramitos/tern-jsx#bb32547"
```
the users who have not installed `git` would have trouble in the installation of `structure-view`. And I think it's reasonable that user just download Atom (`node` `npm` are already builtin) can run my plugin, `git` should not be the necessary one.

So can you publish your `tern-jsx` package to npm market? Or there is any better way to fix this problem?

Thanks.

**Comment by sergioramos** [comment]
fixed in https://github.com/ramitos/jsctags/commit/fdfd930092dfb2aa52f048ac2d6e94eeb9ad6aed
